---
# code: language=ansible
# tasks file for kompose
- name: Kompose | Install binary from github
  ansible.builtin.get_url:
    url: "https://github.com/kubernetes/kompose/releases\
      /download/v{{ kompose_version }}/kompose\
      -{{ ansible_system }}-{{ kompose_architecture }}"
    dest: /usr/local/bin/kompose
    mode: "0755"
