---
# code: language=ansible
- name: Kompose | RHEL | Install package from github
  ansible.builtin.yum:
    name: "{{ kompose_rpm_url }}"
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
