---
# code: language=ansible
namespace: ericsysmin
name: kubernetes
version: 1.0.0
readme: README.md
authors:
  - Eric Anderson <eric.sysmin@gmail.com> (https://ericsysmin.com)
description: Collection of Kubernetes Roles
license_file: 'LICENSE'
tags:
  - kubernetes
  - kubectl
  - kompose
  - k8s
  - cloud
  - gke
  - aks
  - eks
dependencies: {}
repository: https://github.com/ericsysmin/ansible-collection-kubernetes
documentation: https://github.com/ericsysmin/ansible-collection-kubernetes
homepage: https://github.com/ericsysmin/ansible-collection-kubernetes
issues: https://github.com/ericsysmin/ansible-collection-kubernetes/issues
