---
# code: language=ansible

kompose_architecture_mapping:
  x86_64: amd64
  ppc64le: ppc64el
  s390x: s390x
  armv7l: armhf
  aarch64: arm64
  arm64: arm64

kompose_architecture: "{{ kompose_architecture_mapping[ansible_architecture] }}"
