---
# code: language=ansible

- name: Kubectl | Redhat | Add the Kubernetes repository
  ansible.builtin.yum_repository:
    name: kubernetes
    description: Kubernetes
    baseurl: https://pkgs.k8s.io/core:/stable:/v{{ kubectl_version }}/rpm/
    enabled: true
    gpgcheck: true
    gpgkey: https://pkgs.k8s.io/core:/stable:/v{{ kubectl_version }}/rpm/repodata/repomd.xml.key
    file: kubernetes

- name: Kukectl | Redhat | Install kubectl
  ansible.builtin.yum:
    name: kubectl
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
