---
name: ericsysmin.kubernetes.kompose
on:
  push:
    paths:
      - roles/kompose/**
      - molecule/kompose/**
      - .github/workflows/kompose.yml
  pull_request:
    paths:
      - roles/kompose/**
      - molecule/kompose/**
      - .github/workflows/kompose.yml
jobs:
  kompose:
    runs-on: ubuntu-latest
    env:
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1
    strategy:
      fail-fast: true
      matrix:
        molecule_distro:
          - {distro: centos-8, command: /usr/sbin/init}
          - {distro: ubuntu-18.04, command: /lib/systemd/systemd}
          - {distro: ubuntu-20.04, command: /lib/systemd/systemd}
          - {distro: ubuntu-22.04, command: /lib/systemd/systemd}
          - {distro: debian-10, command: /lib/systemd/systemd}
        collection_role:
          - kompose
    steps:
      - name: Check out code
        uses: actions/checkout@v1
        with:
          path: ansible_collections/ericsysmin/kubernetes

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          sudo apt install docker
          python -m pip install --upgrade pip
          pip install molecule yamllint ansible-lint docker

      - name: Run role test
        run: >-
          molecule --version &&
          ansible --version &&
          MOLECULE_COMMAND=${{ matrix.molecule_distro.command }}
          MOLECULE_DISTRO=${{ matrix.molecule_distro.distro }}
          molecule --debug test -s ${{ matrix.collection_role }}
